import type { Product, Designer, Dealer } from "./types";

export const MOCK_DESIGNERS: Designer[] = [
  {
    id: "d1",
    slug: "arne-jacobsen",
    name: "Arne Jacobsen",
    name_zh: "阿納·雅各布森",
    bio: "Danish architect and designer, known for his contribution to architectural functionalism.",
    bio_zh: "丹麥建築師及設計師，以建築功能主義著稱。",
    country: "Denmark",
    born_year: 1902,
    died_year: 1971,
    image_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "d2",
    slug: "hans-wegner",
    name: "Hans J. Wegner",
    name_zh: "漢斯·韋格納",
    bio: "One of the most prolific furniture designers of the 20th century.",
    bio_zh: "二十世紀最多產的家具設計師之一。",
    country: "Denmark",
    born_year: 1914,
    died_year: 2007,
    image_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "d3",
    slug: "le-corbusier",
    name: "Le Corbusier",
    name_zh: "勒·柯比意",
    bio: "Swiss-French architect, designer, and writer.",
    bio_zh: "瑞士-法國建築師、設計師及作家。",
    country: "France",
    born_year: 1887,
    died_year: 1965,
    image_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "d4",
    slug: "alvar-aalto",
    name: "Alvar Aalto",
    name_zh: "阿爾瓦·阿爾托",
    bio: "Finnish architect and designer.",
    bio_zh: "芬蘭建築師及設計師。",
    country: "Finland",
    born_year: 1898,
    died_year: 1976,
    image_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_DEALERS: Dealer[] = [
  {
    id: "dl1",
    name: "Copenhagen Vintage",
    country: "Denmark",
    website: "https://copenhagenvintage.dk",
    contact_email: "info@copenhagenvintage.dk",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "dl2",
    name: "Paris Moderne",
    country: "France",
    website: "https://parismoderne.fr",
    contact_email: "contact@parismoderne.fr",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "dl3",
    name: "Helsinki Design House",
    country: "Finland",
    website: null,
    contact_email: "hello@hdh.fi",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "egg-chair-1958",
    title: "Egg Chair",
    title_zh: "蛋椅",
    description:
      "The iconic Egg Chair designed by Arne Jacobsen in 1958 for the SAS Royal Hotel in Copenhagen. This original piece features its distinctive curved shell upholstered in premium wool fabric with a swivel base.",
    description_zh:
      "阿納·雅各布森於 1958 年為哥本哈根 SAS 皇家酒店設計的經典蛋椅。此原作品以優質羊毛面料包覆獨特的弧形外殼，配備旋轉底座。保存狀態極佳，展現了北歐設計的永恆魅力。",
    price_eur: 8500,
    price_twd: 295000,
    category: "seating",
    style: "scandinavian",
    period: "1950s",
    condition: "excellent",
    dimensions: { width: 86, height: 107, depth: 79, unit: "cm" },
    materials: ["fabric", "metal", "foam"],
    images: [
      { url: "/images/placeholder-product.jpg", alt: "Egg Chair 正面", order: 0 },
      { url: "/images/placeholder-product.jpg", alt: "Egg Chair 側面", order: 1 },
      { url: "/images/placeholder-product.jpg", alt: "Egg Chair 細節", order: 2 },
      { url: "/images/placeholder-product.jpg", alt: "Egg Chair 底座", order: 3 },
    ],
    designer_id: "d1",
    dealer_id: "dl1",
    source_url: null,
    status: "active",
    featured: true,
    created_at: "2025-12-01T00:00:00Z",
    updated_at: "2025-12-01T00:00:00Z",
  },
  {
    id: "2",
    slug: "wishbone-chair-ch24",
    title: "Wishbone Chair CH24",
    title_zh: "Y 椅 CH24",
    description:
      "The CH24 Wishbone Chair by Hans J. Wegner, first manufactured in 1950. Natural oak frame with handwoven paper cord seat.",
    description_zh:
      "漢斯·韋格納設計的 CH24 Y 椅，首次生產於 1950 年。天然橡木框架，配手工編織紙繩座面。椅背的 Y 形結構是其標誌性設計。",
    price_eur: 1200,
    price_twd: 41600,
    category: "seating",
    style: "scandinavian",
    period: "1950s",
    condition: "good",
    dimensions: { width: 55, height: 76, depth: 51, unit: "cm" },
    materials: ["wood", "paper cord"],
    images: [
      { url: "/images/placeholder-product.jpg", alt: "Wishbone Chair 正面", order: 0 },
      { url: "/images/placeholder-product.jpg", alt: "Wishbone Chair 側面", order: 1 },
    ],
    designer_id: "d2",
    dealer_id: "dl1",
    source_url: null,
    status: "active",
    featured: true,
    created_at: "2025-11-28T00:00:00Z",
    updated_at: "2025-11-28T00:00:00Z",
  },
  {
    id: "3",
    slug: "lc4-chaise-longue",
    title: "LC4 Chaise Longue",
    title_zh: "LC4 躺椅",
    description:
      "The LC4 Chaise Longue designed by Le Corbusier, Pierre Jeanneret, and Charlotte Perriand in 1928. Chrome-plated steel frame with black leather upholstery.",
    description_zh:
      "勒·柯比意、皮埃爾·讓納雷與夏洛特·佩里昂於 1928 年設計的 LC4 躺椅。鍍鉻鋼管框架，黑色皮革包覆。此為經典的包浩斯設計代表作。",
    price_eur: 6200,
    price_twd: 214900,
    category: "seating",
    style: "bauhaus",
    period: "1920s",
    condition: "restored",
    dimensions: { width: 56, height: 80, depth: 160, unit: "cm" },
    materials: ["leather", "metal"],
    images: [
      { url: "/images/placeholder-product.jpg", alt: "LC4 躺椅 正面", order: 0 },
      { url: "/images/placeholder-product.jpg", alt: "LC4 躺椅 側面", order: 1 },
      { url: "/images/placeholder-product.jpg", alt: "LC4 躺椅 細節", order: 2 },
    ],
    designer_id: "d3",
    dealer_id: "dl2",
    source_url: null,
    status: "active",
    featured: false,
    created_at: "2025-11-25T00:00:00Z",
    updated_at: "2025-11-25T00:00:00Z",
  },
  {
    id: "4",
    slug: "artek-stool-60",
    title: "Stool 60",
    title_zh: "60 號凳",
    description:
      "The iconic Stool 60 designed by Alvar Aalto in 1933. Birch plywood with the signature L-leg construction.",
    description_zh:
      "阿爾瓦·阿爾托於 1933 年設計的經典 60 號凳。樺木膠合板製成，採用標誌性的 L 型腿結構。此款凳子是芬蘭設計的代表作品。",
    price_eur: 450,
    price_twd: 15600,
    category: "seating",
    style: "scandinavian",
    period: "1930s",
    condition: "good",
    dimensions: { width: 38, height: 44, depth: 38, unit: "cm" },
    materials: ["wood"],
    images: [
      { url: "/images/placeholder-product.jpg", alt: "Stool 60 正面", order: 0 },
      { url: "/images/placeholder-product.jpg", alt: "Stool 60 側面", order: 1 },
    ],
    designer_id: "d4",
    dealer_id: "dl3",
    source_url: null,
    status: "active",
    featured: false,
    created_at: "2025-11-20T00:00:00Z",
    updated_at: "2025-11-20T00:00:00Z",
  },
  {
    id: "5",
    slug: "noguchi-coffee-table",
    title: "Noguchi Coffee Table",
    title_zh: "野口咖啡桌",
    description:
      "The sculptural coffee table designed by Isamu Noguchi in 1947. Walnut base with freeform glass top.",
    description_zh:
      "野口勇於 1947 年設計的雕塑感咖啡桌。胡桃木底座，搭配自由曲線玻璃桌面。此作品完美融合了藝術與功能。",
    price_eur: 3800,
    price_twd: 131700,
    category: "tables",
    style: "mid-century",
    period: "1940s",
    condition: "excellent",
    dimensions: { width: 128, height: 40, depth: 93, unit: "cm" },
    materials: ["wood", "glass"],
    images: [
      { url: "/images/placeholder-product.jpg", alt: "Noguchi 咖啡桌 正面", order: 0 },
      { url: "/images/placeholder-product.jpg", alt: "Noguchi 咖啡桌 俯視", order: 1 },
    ],
    designer_id: null,
    dealer_id: "dl2",
    source_url: null,
    status: "active",
    featured: true,
    created_at: "2025-11-18T00:00:00Z",
    updated_at: "2025-11-18T00:00:00Z",
  },
  {
    id: "6",
    slug: "ph-5-pendant-lamp",
    title: "PH 5 Pendant Lamp",
    title_zh: "PH 5 吊燈",
    description:
      "The PH 5 pendant lamp designed by Poul Henningsen in 1958 for Louis Poulsen. A masterpiece of Scandinavian lighting design.",
    description_zh:
      "保爾·亨寧森於 1958 年為路易斯·波爾森設計的 PH 5 吊燈。北歐照明設計的傑作，提供柔和無眩光的光線。",
    price_eur: 2100,
    price_twd: 72800,
    category: "lighting",
    style: "scandinavian",
    period: "1950s",
    condition: "good",
    dimensions: { width: 50, height: 27, depth: 50, unit: "cm" },
    materials: ["metal"],
    images: [
      { url: "/images/placeholder-product.jpg", alt: "PH 5 吊燈", order: 0 },
      { url: "/images/placeholder-product.jpg", alt: "PH 5 吊燈 細節", order: 1 },
    ],
    designer_id: null,
    dealer_id: "dl1",
    source_url: null,
    status: "active",
    featured: false,
    created_at: "2025-11-15T00:00:00Z",
    updated_at: "2025-11-15T00:00:00Z",
  },
  {
    id: "7",
    slug: "usm-haller-sideboard",
    title: "USM Haller Sideboard",
    title_zh: "USM Haller 邊櫃",
    description:
      "Modular storage system designed by Fritz Haller in 1963. Chrome frame with white metal panels. Two-bay, two-row configuration.",
    description_zh:
      "弗里茨·哈勒於 1963 年設計的模組化收納系統。鍍鉻框架搭配白色金屬板。此為雙列雙排配置，適合居家或辦公使用。",
    price_eur: 2800,
    price_twd: 97000,
    category: "storage",
    style: "bauhaus",
    period: "1960s",
    condition: "excellent",
    dimensions: { width: 153, height: 74, depth: 38, unit: "cm" },
    materials: ["metal"],
    images: [
      { url: "/images/placeholder-product.jpg", alt: "USM Haller 邊櫃 正面", order: 0 },
      { url: "/images/placeholder-product.jpg", alt: "USM Haller 邊櫃 側面", order: 1 },
    ],
    designer_id: null,
    dealer_id: "dl2",
    source_url: null,
    status: "active",
    featured: false,
    created_at: "2025-11-10T00:00:00Z",
    updated_at: "2025-11-10T00:00:00Z",
  },
  {
    id: "8",
    slug: "art-deco-console-table",
    title: "Art Deco Console Table",
    title_zh: "裝飾藝術玄關桌",
    description:
      "A stunning Art Deco console table from the 1930s. Walnut veneer with brass inlay details and elegant tapered legs.",
    description_zh:
      "一張華麗的 1930 年代裝飾藝術風格玄關桌。胡桃木飾面搭配黃銅鑲嵌細節，優雅的錐形桌腿。展現了裝飾藝術時期的奢華美學。",
    price_eur: 4500,
    price_twd: 155900,
    category: "tables",
    style: "art-deco",
    period: "1930s",
    condition: "restored",
    dimensions: { width: 120, height: 80, depth: 35, unit: "cm" },
    materials: ["wood", "metal"],
    images: [
      { url: "/images/placeholder-product.jpg", alt: "裝飾藝術玄關桌 正面", order: 0 },
      { url: "/images/placeholder-product.jpg", alt: "裝飾藝術玄關桌 細節", order: 1 },
    ],
    designer_id: null,
    dealer_id: "dl2",
    source_url: null,
    status: "active",
    featured: false,
    created_at: "2025-11-05T00:00:00Z",
    updated_at: "2025-11-05T00:00:00Z",
  },
  {
    id: "9",
    slug: "industrial-floor-lamp",
    title: "Industrial Floor Lamp",
    title_zh: "工業風落地燈",
    description:
      "A vintage industrial floor lamp from a French factory, circa 1950s. Adjustable arm with cast iron base.",
    description_zh:
      "來自法國工廠的復古工業風落地燈，約 1950 年代。可調節燈臂，鑄鐵底座。帶有歲月痕跡的獨特工業美感。",
    price_eur: 1800,
    price_twd: 62400,
    category: "lighting",
    style: "industrial",
    period: "1950s",
    condition: "fair",
    dimensions: { width: 40, height: 180, depth: 40, unit: "cm" },
    materials: ["metal"],
    images: [
      { url: "/images/placeholder-product.jpg", alt: "工業風落地燈", order: 0 },
    ],
    designer_id: null,
    dealer_id: "dl2",
    source_url: null,
    status: "active",
    featured: false,
    created_at: "2025-11-01T00:00:00Z",
    updated_at: "2025-11-01T00:00:00Z",
  },
  {
    id: "10",
    slug: "french-provincial-armoire",
    title: "French Provincial Armoire",
    title_zh: "法式鄉村衣櫃",
    description:
      "An elegant French Provincial armoire from the late 19th century. Solid oak construction with hand-carved floral details.",
    description_zh:
      "一座優雅的十九世紀末法式鄉村風格衣櫃。實心橡木製成，手工雕刻花卉細節。門板上的銅製五金件保存完好。",
    price_eur: 5600,
    price_twd: 194100,
    category: "storage",
    style: "french-provincial",
    period: "1890s",
    condition: "good",
    dimensions: { width: 140, height: 220, depth: 55, unit: "cm" },
    materials: ["wood", "metal"],
    images: [
      { url: "/images/placeholder-product.jpg", alt: "法式鄉村衣櫃 正面", order: 0 },
      { url: "/images/placeholder-product.jpg", alt: "法式鄉村衣櫃 細節", order: 1 },
      { url: "/images/placeholder-product.jpg", alt: "法式鄉村衣櫃 內部", order: 2 },
    ],
    designer_id: null,
    dealer_id: "dl2",
    source_url: null,
    status: "active",
    featured: false,
    created_at: "2025-10-28T00:00:00Z",
    updated_at: "2025-10-28T00:00:00Z",
  },
  {
    id: "11",
    slug: "brass-desk-lamp-bauhaus",
    title: "Bauhaus Brass Desk Lamp",
    title_zh: "包浩斯黃銅檯燈",
    description:
      "A beautiful Bauhaus-style brass desk lamp from the 1930s. Adjustable shade with push-button switch.",
    description_zh:
      "一盞精美的 1930 年代包浩斯風格黃銅檯燈。可調節燈罩，配有按鈕開關。黃銅表面帶有美麗的氧化色澤。",
    price_eur: 950,
    price_twd: 32900,
    category: "lighting",
    style: "bauhaus",
    period: "1930s",
    condition: "good",
    dimensions: { width: 20, height: 45, depth: 25, unit: "cm" },
    materials: ["metal", "glass"],
    images: [
      { url: "/images/placeholder-product.jpg", alt: "包浩斯黃銅檯燈", order: 0 },
      { url: "/images/placeholder-product.jpg", alt: "包浩斯黃銅檯燈 細節", order: 1 },
    ],
    designer_id: null,
    dealer_id: "dl2",
    source_url: null,
    status: "active",
    featured: false,
    created_at: "2025-10-25T00:00:00Z",
    updated_at: "2025-10-25T00:00:00Z",
  },
  {
    id: "12",
    slug: "ceramic-vase-collection",
    title: "Scandinavian Ceramic Vase Set",
    title_zh: "北歐陶瓷花瓶組",
    description:
      "A set of three handcrafted Scandinavian ceramic vases from the 1960s. Matte glaze in earth tones.",
    description_zh:
      "一組三件的 1960 年代北歐手工陶瓷花瓶。啞光釉面，大地色調。每件花瓶都帶有獨特的手工紋理。",
    price_eur: 680,
    price_twd: 23600,
    category: "decor",
    style: "scandinavian",
    period: "1960s",
    condition: "excellent",
    dimensions: { width: 15, height: 30, depth: 15, unit: "cm" },
    materials: ["ceramic"],
    images: [
      { url: "/images/placeholder-product.jpg", alt: "北歐陶瓷花瓶組", order: 0 },
    ],
    designer_id: null,
    dealer_id: "dl3",
    source_url: null,
    status: "active",
    featured: false,
    created_at: "2025-10-20T00:00:00Z",
    updated_at: "2025-10-20T00:00:00Z",
  },
];

export function getDesignerById(id: string): Designer | undefined {
  return MOCK_DESIGNERS.find((d) => d.id === id);
}

export function getDealerById(id: string): Dealer | undefined {
  return MOCK_DEALERS.find((d) => d.id === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return MOCK_PRODUCTS.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, count = 4): Product[] {
  return MOCK_PRODUCTS.filter(
    (p) =>
      p.id !== product.id &&
      (p.category === product.category || p.style === product.style)
  ).slice(0, count);
}
